# Generated by Django 4.0.7 on 2022-08-28 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.models.multitenancy


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtailcore", "0078_add_default_tenant"),
        ("wagtailusers", "0010_userprofile_updated_comments_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="native_tenant",
            field=models.ForeignKey(
                default=wagtail.models.multitenancy.get_default_tenant_id,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailcore.tenant",
                verbose_name="native tenant",
            ),
        ),
    ]
