# Generated by Django 4.0.7 on 2022-08-28 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.models.multitenancy


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtailcore", "0078_add_default_tenant"),
        ("wagtailusers", "0011_userprofile_native_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSecondaryTenantAccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_user_access",
                        to="wagtailcore.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_tenants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "tenant")},
            },
        ),
    ]
