# Generated by Django 4.0.7 on 2022-08-30 11:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.multitenancy


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("wagtailcore", "0082_modellogentry_native_tenant_and_more"),
        ("wagtailusers", "0012_usersecondarytenantaccess"),
    ]

    operations = [
        migrations.CreateModel(
            name="WagtailGroup",
            fields=[
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wagtailgroup",
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                ("is_global", models.BooleanField(default=False)),
                (
                    "native_tenant",
                    models.ForeignKey(
                        default=wagtail.multitenancy.get_default_tenant_id,
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.tenant",
                        verbose_name="native tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
