# Generated by Django 4.0.7 on 2022-08-28 16:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.models.multitenancy


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0079_collection_native_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="native_tenant",
            field=models.ForeignKey(
                default=wagtail.multitenancy.get_default_tenant_id,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.tenant",
                verbose_name="native tenant",
            ),
        ),
    ]
