# Generated by Django 4.0.7 on 2022-08-28 17:04

from django.db import migrations, models
import django.db.models.deletion
import wagtail.models.multitenancy


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0081_site_native_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="modellogentry",
            name="native_tenant",
            field=models.ForeignKey(
                default=wagtail.multitenancy.get_default_tenant_id,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailcore.tenant",
                verbose_name="native tenant",
            ),
        ),
        migrations.AddField(
            model_name="pagelogentry",
            name="native_tenant",
            field=models.ForeignKey(
                default=wagtail.multitenancy.get_default_tenant_id,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailcore.tenant",
                verbose_name="native tenant",
            ),
        ),
    ]
